# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: conf.py
build:
  os: "ubuntu-22.04"
  apt_packages:
    - dcraw
    - imagemagick
    - fig2dev
    - texlive
    - xzdec
    - fig2ps
    - gv
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - mkdir ~/.config
      - mkdir ~/.config/ImageMagick
      - cp /etc/ImageMagick-*/* ~/.config/ImageMagick
      - ls -l ~/.config/ImageMagick
      - perl -p -i -e 's/\"none\"/\"read\|write\"/g' ~/.config/ImageMagick/policy.xml

conda:
  environment: environment.yml

submodules:
  include:
    - getfem
  recursive: true
