# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - automake
    - libtool
    - make
    - g++
    - libqd-dev
    - libqhull-dev
    - libmumps-seq-dev
    - liblapack-dev
    - libopenblas-dev
    - libpython3-dev
    - dcraw
    - imagemagick
    - fig2dev
    - texlive
    - xzdec
    - fig2ps
    - gv
    - python3-vtk7
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - mkdir ~/.config
      - mkdir ~/.config/ImageMagick
      - cp /etc/ImageMagick-*/* ~/.config/ImageMagick
      - ls -l .config/ImageMagick
      - perl -p -i -e 's/^.*"EPS".*\n//g' ~/.config/ImageMagick/policy.xml
      - perl -p -i -e 's/^.*"PS".*\n//g'  ~/.config/ImageMagick/policy.xml
      - perl -p -i -e 's/^.*"PDF".*\n//g' ~/.config/ImageMagick/policy.xml
      - perl -p -i -e 's/^.*"XPS".*\n//g' ~/.config/ImageMagick/policy.xml
      - echo $MAGICK_CONFIGURE_PATH
      - cd getfem && bash autogen.sh && ./configure --with-pic && cd doc/sphinx && make images

sphinx:
   configuration: conf.py

conda:
  environment: environment.yml

submodules:
  include:
    - getfem
  recursive: true
