language: python
sudo: false
dist: bionic
cache:
  directories:
  - $HOME/.cache/pip
env:
  global:
  - SPHINXINTL_TRANSIFEX_USERNAME=api
  - SPHINXINTL_TRANSIFEX_PROJECT_NAME=getfem-53-1
  - secure: "FAA/tP/UJW4s6McgKJkFJnRz3SLdKUuixAT3gc+60alauI8awhHwPDf/Oe1QkoAXkUzOnr/RR9RUAysBaZ5rG4Rhh5kIJcAX+b30/4k6XXRWih7skSyrznyUBlCB/YfEIip8lV5U+GpL7RVEWwB/LOWPiKcMV729lNm25xxbWchlU2XcXd2/gj0DBF4FfKB/A8vQZTpIZkvE8+Ignr99h3Ye/exSr65ymKI2e53RXeKhGnU63Wi78Nh4bm8UTgdnxXaQt1xaDRQyQl4x0tgNKNMycvGncRBeJQ8l/k9HfavMqDt59NC0qUcDRboM1yOe7L20jfWBkb6h3VBsn4JBYUCJCiuG1vZaUda1KdxqizNq7oP8UlTkF73WxjNDK4Y+3P9esZVE3qIoNi4nDC+JMg/EUCabCiS2SYLbQbaPqz3GUO9CbcdX+ZiZr35N66g5cIqD24dDAVKHTW6zTDjtpvGuJWWS60UUfm4VBWSTL5dJAoT74F5GtdgnmQqywYEjcaFB6e/7GNY7KYJU8KQKZDUy+HdRtcub9Y+wrseCmBsvjPgwMShtPCPeK16cVxS39sOUhLuNtDKa/suH+2eW6P50JsfVpJOxeetraSR4wxtn9M6wuCPlds6sFuga829WYUYMREDiC1kr6D6dbB8C5go8w3WXRdMTQTRfUkRGTc8="
before_install:
- openssl aes-256-cbc -K $encrypted_a10c131499f7_key -iv $encrypted_a10c131499f7_iv -in .secrets/key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sudo apt-get install -y --no-install-recommends automake
- sudo apt-get install -y --no-install-recommends libtool
- sudo apt-get install -y --no-install-recommends make
- sudo apt-get install -y --no-install-recommends g++
- sudo apt-get install -y --no-install-recommends libqd-dev
- sudo apt-get install -y --no-install-recommends libqhull-dev
- sudo apt-get install -y --no-install-recommends libmumps-seq-dev
- sudo apt-get install -y --no-install-recommends liblapack-dev
- sudo apt-get install -y --no-install-recommends libopenblas-dev
- sudo apt-get install -y --no-install-recommends libpython3-dev
- sudo apt-get install -y --no-install-recommends ufraw
- sudo apt-get install -y --no-install-recommends imagemagick
- sudo apt-get install -y --no-install-recommends fig2dev
- sudo apt-get install -y --no-install-recommends texlive
- sudo apt-get install -y --no-install-recommends xzdec
- sudo apt-get install -y --no-install-recommends fig2ps
- sudo apt-get install -y --no-install-recommends gv
addons:
  apt:
    update: true
install:
- git branch -a
- git checkout master  # attach this repo
- git submodule init
- git submodule update
- (cd getfem; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
- pip install -U pip setuptools
- pip install -r ./requirements.txt
script:
- cd getfem
- bash autogen.sh
- ./configure --with-pic --enable-python3=yes
- make -j8  >  make.log
- sudo perl -p -i -e 's/^.*"EPS".*\n//g' /etc/ImageMagick-*/policy.xml
- sudo perl -p -i -e 's/^.*"PS".*\n//g'  /etc/ImageMagick-*/policy.xml
- sudo perl -p -i -e 's/^.*"PDF".*\n//g' /etc/ImageMagick-*/policy.xml
- sudo perl -p -i -e 's/^.*"XPS".*\n//g' /etc/ImageMagick-*/policy.xml
- rm -rf ../doc
- rm -rf ../interface
- cp -r doc ../doc
- cp -r interface ../interface
- cd ../
- (cd doc/sphinx; make gettext; make latex; make images)
after_success:
- git branch -a
- git checkout master  # attach this repo
- git config --global user.email "getfem-auto-update"
- git config --global user.name "getfem-auto-update"
- rm -rf doc/sphinx/locale
- rm -rf doc/sphinx/build
- rm -rf interface
- git add .
- |
  git commit -m "[skip ci] by Travis CI (JOB $TRAVIS_JOB_NUMBER)
  https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
- git remote -v
- git remote add github git@github.com:getfem-doc/getfem-doc-translations.git
- git push github master
