language: python
sudo: false
dist: bionic
cache:
  directories:
  - $HOME/.cache/pip
env:
  global:
  - SPHINXINTL_TRANSIFEX_USERNAME=api
  - SPHINXINTL_TRANSIFEX_PROJECT_NAME=getfem
  - secure: "MMzcx5hsN4jlDi7W9N4LJUOvhvtni1hTar5DTj1FUKUDvUTp+8XIjkulHPKtluOxeHu36gXIB4FqZEoZrh+Q1V9WbcbdGNcTH+D5ya056P6lu+xD8X2TqlY/1WYsBAlnaw0dYu786lka9vXomBtFtjxnvoZuk94Jo4xP9yn26amNKv7TXAbLmT98S86LZhNwmwT2NED1dRHoQI358zL8SsLBG45aIUqQrd17C2FhQzX0YlGbfcdwcmNOcy41ToGMqXtG0mRyUZsMntuND55gtlzPJ2H5JlYfvjnLUnqbEebF+NFpGwHDKGErwN6UV24N7n4fmo0RjzytGtUyZmKSzgw712ESNmTa3PzJZZvBXJK5aTMfYag/I91S91ToNXL8JAfVATRSpAWs92PdRrOqmvm3DvOxHY6Fv48ap3LsE4dGo0cPUrQ9t+zkOe5xtIm+eyR38Nu5HioRF8xLdx5+PSm8AP0C0zeGwO0fWtfs2QxNi7robwboDk6aem7c59nFJ0Ez3N/pQRIOMbBYi6p9rpz48tNq6+1bBhz43TSsj0mrBhoR8n1wiXdA53qwIBEnQ5pF2u+AODhA/rutd2n1z8N7vD+ShEC5tNKFI6+8ITc35pdQEMTLQ7JJXJ+iDs7KBgG8LLOdUB6P2D/kKDL3QKY0Yvn2yLb6L1yiKakHoUQ="
before_install:
- openssl aes-256-cbc -K $encrypted_a10c131499f7_key -iv $encrypted_a10c131499f7_iv -in .secrets/key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sudo apt-get install -y --no-install-recommends automake
- sudo apt-get install -y --no-install-recommends libtool
- sudo apt-get install -y --no-install-recommends make
- sudo apt-get install -y --no-install-recommends g++
- sudo apt-get install -y --no-install-recommends libqd-dev
- sudo apt-get install -y --no-install-recommends libqhull-dev
- sudo apt-get install -y --no-install-recommends libmumps-seq-dev
- sudo apt-get install -y --no-install-recommends liblapack-dev
- sudo apt-get install -y --no-install-recommends libopenblas-dev
- sudo apt-get install -y --no-install-recommends libpython3-dev
- sudo apt-get install -y --no-install-recommends ufraw
- sudo apt-get install -y --no-install-recommends imagemagick
- sudo apt-get install -y --no-install-recommends fig2dev
- sudo apt-get install -y --no-install-recommends texlive-full
- sudo apt-get install -y --no-install-recommends xzdec
- sudo perl -p -i -e 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-*/policy.xml
- pip install -r requirements.txt
addons:
  apt:
    update: true
install:
- git branch -a
- git submodule init
- git submodule update
- (cd getfem; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
script:
- cd getfem
- bash autogen.sh
- ./configure --with-pic --enable-python3=yes
- make -j8
- make -j8 check
- sudo make install
- make html
- rm -rf ../doc
- rm -rf ../interface
- cp -r doc ../doc
- cp -r interface ../interface
- cd ../
- rm -rf doc/sphinx/loca- rm -rf doc/sphinx/localele
- rm -rf doc/sphinx/build
- git add doc
- sh ./locale/update.sh
after_success:
- git config --global user.email "getfem-auto-update"
- git config --global user.name "getfem-auto-update"
- git add .
- |
  git commit -m "[skip ci] by Travis CI (JOB $TRAVIS_JOB_NUMBER)
  https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
- git remote -v
- git remote add github git@github.com:getfem-doc/getfem-doc-translations.git
- git push github master
