language: python
sudo: false
dist: bionic
cache:
  directories:
  - $HOME/.cache/pip
env:
  global:
  - SPHINXINTL_TRANSIFEX_USERNAME=api
  - SPHINXINTL_TRANSIFEX_PROJECT_NAME=getfem-53-1
  - secure: "FAA/tP/UJW4s6McgKJkFJnRz3SLdKUuixAT3gc+60alauI8awhHwPDf/Oe1QkoAXkUzOnr/RR9RUAysBaZ5rG4Rhh5kIJcAX+b30/4k6XXRWih7skSyrznyUBlCB/YfEIip8lV5U+GpL7RVEWwB/LOWPiKcMV729lNm25xxbWchlU2XcXd2/gj0DBF4FfKB/A8vQZTpIZkvE8+Ignr99h3Ye/exSr65ymKI2e53RXeKhGnU63Wi78Nh4bm8UTgdnxXaQt1xaDRQyQl4x0tgNKNMycvGncRBeJQ8l/k9HfavMqDt59NC0qUcDRboM1yOe7L20jfWBkb6h3VBsn4JBYUCJCiuG1vZaUda1KdxqizNq7oP8UlTkF73WxjNDK4Y+3P9esZVE3qIoNi4nDC+JMg/EUCabCiS2SYLbQbaPqz3GUO9CbcdX+ZiZr35N66g5cIqD24dDAVKHTW6zTDjtpvGuJWWS60UUfm4VBWSTL5dJAoT74F5GtdgnmQqywYEjcaFB6e/7GNY7KYJU8KQKZDUy+HdRtcub9Y+wrseCmBsvjPgwMShtPCPeK16cVxS39sOUhLuNtDKa/suH+2eW6P50JsfVpJOxeetraSR4wxtn9M6wuCPlds6sFuga829WYUYMREDiC1kr6D6dbB8C5go8w3WXRdMTQTRfUkRGTc8="
addons:
  apt:
    update: true
before_install:
- sudo apt-get install -y --no-install-recommends transifex-client
install:
- pip install -U pip setuptools
- pip install -r ./requirements.txt
script:
- cd doc/sphinx
- (tx init --token=$TX_TOKEN --force --no-interactive;
   sphinx-intl create-transifexrc;
   sphinx-build -T -b gettext source locale ;
   sphinx-intl update-txconfig-resources -p locale -d source/locale;
   cat .tx/config;
   tx push -s --skip;
   rm -rf source/locale/ja;
   tx pull -l ja)
