name: getfem-auto-update
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: update
      env:
        ACCOUNT: tkoyama010
        ORGANIZATION: getfem-doc
        NAME: "getfem-auto-update"
        EMAIL: "getfem-auto-update"
        REPO: getfem-doc-translations
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: getfem-53-1
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        sudo apt update
        sudo apt-get install python3-venv
        sudo apt-get install -y --no-install-recommends automake
        sudo apt-get install -y --no-install-recommends libtool
        sudo apt-get install -y --no-install-recommends make
        sudo apt-get install -y --no-install-recommends g++
        sudo apt-get install -y --no-install-recommends libqd-dev
        sudo apt-get install -y --no-install-recommends libqhull-dev
        sudo apt-get install -y --no-install-recommends libmumps-seq-dev
        sudo apt-get install -y --no-install-recommends liblapack-dev
        sudo apt-get install -y --no-install-recommends libopenblas-dev
        sudo apt-get install -y --no-install-recommends libpython3-dev
        sudo apt-get install -y --no-install-recommends ufraw
        sudo apt-get install -y --no-install-recommends imagemagick
        sudo apt-get install -y --no-install-recommends fig2dev
        sudo apt-get install -y --no-install-recommends texlive
        sudo apt-get install -y --no-install-recommends xzdec
        sudo apt-get install -y --no-install-recommends fig2ps
        sudo apt-get install -y --no-install-recommends gv
        python3 -m venv ../.venv
        source ../.venv/bin/activate
        git submodule update
        (cd getfem; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
        pip install -U pip setuptools
        pip install -r ./requirements.txt
        cd getfem
        bash autogen.sh
        ./configure --with-pic --enable-python3=yes
        make -j8  >  make.log
        sudo perl -p -i -e 's/^.*"EPS".*\n//g' /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"PS".*\n//g'  /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"PDF".*\n//g' /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"XPS".*\n//g' /etc/ImageMagick-*/policy.xml
        pip install sphinx-intl[transifex]
        (cd doc/sphinx;
         make latex;
         make images;
         sphinx-intl create-transifexrc;
         sphinx-build -T -b gettext source locale ;
         sphinx-intl update-txconfig-resources -p locale -d source/locale;
         cat .tx/config;
         tx push -s --skip;
         rm -rf source/locale/ja;
         tx pull -l ja)
        rm -rf ../doc
        rm -rf ../interface
        rm -rf doc/sphinx/locale/.doctrees
        cp -r doc ../doc
        cp -r interface ../interface
        cd ../
        git branch -a
        git checkout master
        git config --global user.email $EMAIL
        git config --global user.name $NAME
        git add .
        git commit --allow-empty -m ":green_heart: $JOB_ID
        $HTML_URL"
        git remote -v
        git remote add github git@github.com:$ORGANIZATION/$REPO.git
        git push github master
        deactivate
