name: getfem-auto-update
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
jobs:
  script:
    runs-on: ubuntu-20.04
    steps:
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: install
      run: |
        sudo apt update
        sudo apt-get install -y --no-install-recommends automake
        sudo apt-get install -y --no-install-recommends libtool
        sudo apt-get install -y --no-install-recommends make
        sudo apt-get install -y --no-install-recommends g++
        sudo apt-get install -y --no-install-recommends libqd-dev
        sudo apt-get install -y --no-install-recommends libqhull-dev
        sudo apt-get install -y --no-install-recommends libmumps-seq-dev
        sudo apt-get install -y --no-install-recommends liblapack-dev
        sudo apt-get install -y --no-install-recommends libopenblas-dev
        sudo apt-get install -y --no-install-recommends libpython3-dev
        sudo apt-get install -y --no-install-recommends imagemagick
        sudo apt-get install -y --no-install-recommends fig2dev
        sudo apt-get install -y --no-install-recommends texlive
        sudo apt-get install -y --no-install-recommends xzdec
        sudo apt-get install -y --no-install-recommends fig2ps
        sudo apt-get install -y --no-install-recommends gv
        sudo apt-get install -y --no-install-recommends python3-pip
        sudo apt-get install -y --no-install-recommends sphinx-intl
        sudo apt-get install -y --no-install-recommends python3-venv
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        mv tx /usr/local/bin/tx
    - name: update
      env:
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: getfem-53-1
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        git submodule update
        python3 -m venv /home/runner/work/venv
        source /home/runner/work/venv/bin/activate
        (cd getfem; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
        pip3 config set global.index-url https://pypi.python.org/simple/
        pip3 install -U pip setuptools
        pip3 install -r ./requirements.txt
        cd getfem
        bash autogen.sh
        ./configure --prefix=/home/runner/work/venv --with-pic
        make -j8  >  make.log
        sudo make install
        sudo perl -p -i -e 's/^.*"EPS".*\n//g' /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"PS".*\n//g'  /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"PDF".*\n//g' /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"XPS".*\n//g' /etc/ImageMagick-*/policy.xml
        (cd doc/sphinx;
         make latex;
         make images;
         sphinx-build -T -b gettext source locale ;
         sphinx-intl update-txconfig-resources -p locale -d source/locale --transifex-organization-name="tkoyama010";
         cat .tx/config;
         tx push -s --skip;
         rm -rf source/locale/ja source/locale/pt_BR || true;
         tx pull --silent -f -l ja,pt_BR)
        rm -rf ../doc
        rm -rf doc/sphinx/locale/.doctrees
        cp -r doc ../doc
        cd ../
        deactivate
    - name: git_config
      env:
        NAME: "getfem-auto-update"
        EMAIL: "getfem-auto-update"
      run: |
        git branch -a
        git config --global user.email $EMAIL
        git config --global user.name $NAME
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[ci skip] ${{ steps.jobs.outputs.job_id }}"
