name: getfem-auto-update
on:
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
    branches:
      - master
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: install
      run: |
        sudo apt update
        sudo apt-get install python3-pip
        sudo apt-get install -y --no-install-recommends automake
        sudo apt-get install -y --no-install-recommends libtool
        sudo apt-get install -y --no-install-recommends make
        sudo apt-get install -y --no-install-recommends g++
        sudo apt-get install -y --no-install-recommends libqd-dev
        sudo apt-get install -y --no-install-recommends libqhull-dev
        sudo apt-get install -y --no-install-recommends libmumps-seq-dev
        sudo apt-get install -y --no-install-recommends liblapack-dev
        sudo apt-get install -y --no-install-recommends libopenblas-dev
        sudo apt-get install -y --no-install-recommends libpython3-dev
        sudo apt-get install -y --no-install-recommends ufraw
        sudo apt-get install -y --no-install-recommends imagemagick
        sudo apt-get install -y --no-install-recommends fig2dev
        sudo apt-get install -y --no-install-recommends texlive
        sudo apt-get install -y --no-install-recommends xzdec
        sudo apt-get install -y --no-install-recommends fig2ps
        sudo apt-get install -y --no-install-recommends gv
        git submodule update
        (cd getfem; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
        pip3 install -U setuptools
        pip3 install -U pip
        pip3 install -U distribute
        pip3 install -r ./requirements.txt
        cd getfem
        bash autogen.sh
        ./configure --with-pic --enable-python3=yes
        make -j8  >  make.log
        sudo make install
        cd ../
    - name: update
      env:
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: getfem-53-1
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
        LOCAL_PYTHON_PATH: "/home/runner/.local/bin"
        PYTHONPATH: "/usr/local/lib/python3.6/site-packages:$PYTHONPATH"
      run: |
        cd getfem
        sudo perl -p -i -e 's/^.*"EPS".*\n//g' /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"PS".*\n//g'  /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"PDF".*\n//g' /etc/ImageMagick-*/policy.xml
        sudo perl -p -i -e 's/^.*"XPS".*\n//g' /etc/ImageMagick-*/policy.xml
        (cd doc/sphinx;
         make latex;
         make images;
         $LOCAL_PYTHON_PATH/sphinx-intl create-transifexrc;
         $LOCAL_PYTHON_PATH/sphinx-build -T -b gettext source locale ;
         $LOCAL_PYTHON_PATH/sphinx-intl update-txconfig-resources -p locale -d source/locale;
         cat .tx/config;
         $LOCAL_PYTHON_PATH/tx push -s --skip;
         rm -rf source/locale/ja;
         $LOCAL_PYTHON_PATH/tx pull -l ja)
        rm -rf ../doc
        rm -rf ../interface
        rm -rf doc/sphinx/locale/.doctrees
        cp -r doc ../doc
        cp -r interface ../interface
        cd ../
    - name: git_config
      run: |
        git branch -a
        git checkout master
        git config --global user.email $GITHUB_REPOSITORY
        git config --global user.name $GITHUB_REPOSITORY
    - name: commit
      env:
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
      run: |
        git add .
        git commit --allow-empty -m ":green_heart: $JOB_ID
        $HTML_URL"
        git remote -v
        git remote add github git@github.com:$GITHUB_REPOSITORY.git
        git push github master
